### ISSUE TITLE
getNextValSet() should be executed after execBlock() is done

### ISSUE THREAD

**Issue by juniway** [Baptist-Publication/chorus#1]
s.blockExecutable.BeginBlock(block, eventSwitch, blockPartsHeader)
	s.execBlock(eventSwitch, block, round)
	s.blockExecutable.EndBlock(block, eventSwitch, blockPartsHeader, changedValidators, nextValSet)
nextValSet := s.getNextValSet(valSet, bheader.Height, round)

**Comment by cjqpker** [comment]
fixed in branch c4
